#!/bin/bash

# Search for python3 installation
if ! command -v brew &> /dev/null ; then
    echo "ERROR: Homebrew not on PATH!"
    exit 1
fi
if ! brew ls --versions python > /dev/null; then
    echo "ERROR: python3 not found"
    exit 1
fi

VERSION=$(brew ls --versions toggle-wifi | awk '{ print $2 }')
HOMEBREW_PREFIX=$(brew --prefix)
python3 $HOMEBREW_PREFIX/Cellar/toggle-wifi/$VERSION/toggle-wifi.py
