#!/bin/bash

if ! test -f "/opt/homebrew/bin/brew"; then
    if ! test -f "/usr/local/bin/brew"; then
        echo "ERROR: Homebrew not found!"
        exit 23
    else
        HOMEBREW_PREFIX="/usr/local"
    fi
else
    HOMEBREW_PREFIX="/opt/homebrew"
fi

VERSION=$($HOMEBREW_PREFIX/bin/brew ls --versions toggle-wifi | awk '{ print $2 }' | head -n 1)
$HOMEBREW_PREFIX/bin/python3 $HOMEBREW_PREFIX/Cellar/toggle-wifi/$VERSION/toggle-wifi.py
